-- ============================================================
-- ตาราง refund: เก็บประวัติการคืนเงินสำหรับรายการที่ยกเลิก
-- (แอดมินยกเลิก / ไม่ได้รับการอนุมัติจนรายการหมดอายุ)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.refund (
  refund_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id integer NOT NULL REFERENCES public.booking(booking_id) ON DELETE CASCADE,
  amount numeric NOT NULL DEFAULT 0,
  refund_slip text,
  note text,
  admin_id integer,
  refund_date timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_refund_booking_id ON public.refund(booking_id);

COMMENT ON TABLE public.refund IS 'ประวัติการคืนเงิน (ผู้ดูแลระบบ)';

-- ==============================
-- RLS policies
-- ==============================
ALTER TABLE public.refund ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "refund_all_admin" ON public.refund;
CREATE POLICY "refund_all_admin" ON public.refund FOR ALL
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "refund_select_customer" ON public.refund;
CREATE POLICY "refund_select_customer" ON public.refund FOR SELECT
  USING (
    booking_id IN (
      SELECT booking_id FROM public.booking
      WHERE customer_id IN (
        SELECT customer_id FROM public.customer
        WHERE auth_user_id = auth.uid()
      )
    )
  );